embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384
device: CPU
index:
  ef_construction: 200
  M: 16
  flush_threshold: 1000  # Flush index to disk after this many nodes in memory
vector_db:
  file_path: ../vector_db
  dimension: 384
  capacity: 1000000
